language: android
jdk:
    - oraclejdk7
android:
  components:
    - build-tools-19.1.0
    - android-19
    - extra
    - addon
    - sys-img-armeabi-v7a-android-19
before_install:
 - chmod +x gradlew

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
    - gradle wrapper
    - gradle build
    - gradle assembleAndroidTest
    - adb wait-for-device push ./TesterLib/ build/outputs/apk/TesterLib-debug-androidTestunaligned.apk /data/local/tmp/apimatic.hopto.org.test
    - adb wait-for-device shell pm install -r "/data/ local/tmp/apimatic.hopto.org.test"
    - adb wait-for-device shell am instrument -w -r   -e package apimatic.hopto.org -e debug false apimatic.hopto.org.test/ android.support.test.runner.AndroidJUnitRunner